"""empty message

Revision ID: 56037c4487a7
Revises: aa5a64be0cb1
Create Date: 2021-03-25 20:42:09.804935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56037c4487a7'
down_revision = 'aa5a64be0cb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'author2', schema='news')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('author2', sa.VARCHAR(), autoincrement=False, nullable=True), schema='news')
    # ### end Alembic commands ###
