"""empty message

Revision ID: 68f410fab77a
Revises: 7e542d51870b
Create Date: 2021-03-24 22:03:53.386640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68f410fab77a'
down_revision = '7e542d51870b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'articles', ['id'], schema='news')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'articles', schema='news', type_='unique')
    # ### end Alembic commands ###
