"""empty message

Revision ID: 7e542d51870b
Revises: 9e7e7f443cde
Create Date: 2021-03-24 16:34:21.176222

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7e542d51870b'
down_revision = '9e7e7f443cde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'published_date2', schema='news')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('published_date2', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True), schema='news')
    # ### end Alembic commands ###
