"""init

Revision ID: 82b7319a6d89
Revises: 
Create Date: 2021-03-24 00:43:47.882606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82b7319a6d89'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    op.execute('create schema if not exists news;')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('img_url', sa.String(), nullable=True),
    sa.Column('published_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='news'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('articles', schema='news')
    # ### end Alembic commands ###
    op.execute('drop schema if not exists news;')
