"""empty message

Revision ID: 953cfc2c2253
Revises: 68f410fab77a
Create Date: 2021-03-24 22:04:48.562063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '953cfc2c2253'
down_revision = '68f410fab77a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('articles_id_key', 'articles', schema='news', type_='unique')
    op.create_unique_constraint(None, 'articles', ['id', 'title'], schema='news')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'articles', schema='news', type_='unique')
    op.create_unique_constraint('articles_id_key', 'articles', ['id'], schema='news')
    # ### end Alembic commands ###
