"""empty message

Revision ID: 9e7e7f443cde
Revises: 
Create Date: 2021-03-24 16:34:11.071479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e7e7f443cde'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('published_date2', sa.DateTime(timezone=True), nullable=True), schema='news')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'published_date2', schema='news')
    # ### end Alembic commands ###
