"""empty message

Revision ID: df883e9a8286
Revises: fb1a04147f93
Create Date: 2021-03-24 22:52:09.409338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df883e9a8286'
down_revision = 'fb1a04147f93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('source_id', sa.Integer(), nullable=True), schema='news')
    op.create_foreign_key(None, 'articles', 'sources', ['source_id'], ['id'], source_schema='news', referent_schema='news')
    op.create_unique_constraint(None, 'sources', ['id'], schema='news')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sources', schema='news', type_='unique')
    op.drop_constraint(None, 'articles', schema='news', type_='foreignkey')
    op.drop_column('articles', 'source_id', schema='news')
    # ### end Alembic commands ###
