"""empty message

Revision ID: fb1a04147f93
Revises: 953cfc2c2253
Create Date: 2021-03-24 22:51:50.031014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb1a04147f93'
down_revision = '953cfc2c2253'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('img_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('slug'),
    schema='news'
    )
    op.drop_constraint('articles_id_title_key', 'articles', schema='news', type_='unique')
    op.create_unique_constraint(None, 'articles', ['title'], schema='news')
    op.create_unique_constraint(None, 'articles', ['id'], schema='news')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'articles', schema='news', type_='unique')
    op.drop_constraint(None, 'articles', schema='news', type_='unique')
    op.create_unique_constraint('articles_id_title_key', 'articles', ['id', 'title'], schema='news')
    op.drop_table('sources', schema='news')
    # ### end Alembic commands ###
